name: "Pipeline Workflow"
run-name: "Pipeline Workflow RN"
on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build!!!"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test!!!"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy!!!"